export type { SessionMeta, CanvasMeta, ProjectMeta, WorkspaceEntry, Workspace } from './types'
export { FilePanel } from './FilePanel'
export { FloatingEditor } from './FloatingEditor'
export { ConversationList } from './ConversationList'
export { CanvasBar } from './CanvasBar'
export { useWorkspace, type WorkspaceApi } from './useWorkspace'
